### ISSUE TITLE
Broken due to upstream changes

### ISSUE THREAD

**Issue by dcelasun** [icculus/inline-reddit#3]
Something changed on reddit's end on 1 May and `recache` just fails silently now.

**Comment by flwyd** [comment]
Example: https://inline-reddit.com/feed/?subreddit=pics returns 503 with error message `Couldn't get the reddit RSS feed. Try again later.`

I'd love to see this fixed; Inline Reddit is a great service.

**Comment by icculus** [comment]
It's not broken so much as we appear to be blocked.

When we try to grab an RSS feed from reddit, they reply with this HTML (converted to Markdown for this comment)...


> # whoa there, pardner!
> 
> reddit's awesome and all, but you may have a bit of a problem.
>
> Make sure your User-Agent is not empty, is something unique and descriptive and try again. if you're supplying an alternate User-Agent string,
> try changing back to default as that can sometimes result in a block.
>
> You can read Reddit's Terms of Service [here](https://www.reddit.com/wiki/api/).
>
> if you think that we've incorrectly blocked you or you would like to discuss
easier ways to get the data you want, please contact us at `[mailto link removed]` this email address.
>
> when contacting us, please include your ip address which is: `[removed]` and reddit account

I guess I'll try contacting them...but I'm not super optimistic here. We'll see what happens next.

**Comment by CopperF0x** [comment]
@icculus - a user of [reddit-top-rss](https://github.com/johnwarne/reddit-top-rss) found a fix for the same issue, see their code solution here - https://github.com/johnwarne/reddit-top-rss/issues/17#issuecomment-1537833174

**Comment by dcelasun** [comment]
Yes, it's not an IP block and affects self hosted instances as well. We just need a reasonable User Agent.

**Comment by icculus** [comment]
It works! We are live again!

I'll put this in revision control shortly and close this issue, but it is already working again now.
